apiVersion: skaffold/v4beta5
kind: Config
metadata:
  name: deploy-run-quickstart
profiles:
- name: dev
  manifests:
    rawYaml:
    - run-service-dev.yaml
- name: prod
  manifests:
    rawYaml:
    - run-service-prod.yaml
deploy:
  cloudrun: {}
verify:
- name: verify-endpoint-test
  container:
    name: alpine
    image: alpine
    command: ["/bin/sh"]
    args: ["-c", "wget ${CLOUD_RUN_SERVICE_URLS}"]
customActions:
- name: postdeploy-make-cloud-run-services-public
  containers:
  - name: gcloud
    image: 'gcr.io/google.com/cloudsdktool/google-cloud-cli:latest'
    command: ["/bin/sh"]
    args: ["-c", "gcloud run services add-iam-policy-binding ${CLOUD_RUN_SERVICE} --member='allUsers' --role=roles/run.invoker --region=${CLOUD_RUN_LOCATION}"]
